### ISSUE TITLE
connection reset by peers

### ISSUE THREAD

**Issue by roboticsai** [neobotix/neo_localization#3]
I am trying to run the ros controllers with hardware interface with neo_localization node. But whenenver i try to run them both i'm getting this kinds of errors:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Success
[bini_hw_main-2] process has died [pid 6146, exit code -6, cmd /home/ubuntu/bini_ws/devel/lib/bini_controllers/bini_hw_main base_controller/odom:=odom base_controller/cmd_vel:=cmd_vel __name:=bini_hw_main __log:=/home/ubuntu/.ros/log/dd4f76fe-1514-11ec-80cc-8d7ae55a0400/bini_hw_main-2.log].
log file: /home/ubuntu/.ros/log/dd4f76fe-1514-11ec-80cc-8d7ae55a0400/bini_hw_main-2*.log
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:
```
Here the hw_interface is connected with the motor controller with usb interface.
How should i solve this error?
Environment:
ROS noetic
Ubuntu server 20.04
Raspberry pi 4B 8GB RAM

**Comment by padhupradheep** [comment]
Hey, I believe this issue is related to ROS hardware interface and does not relate anyways to the neo_localization. Please raise an issue in [ros_controllers](https://github.com/ros-controls/ros_control), may be tthe folks over there can help you.
